name: da3afes
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  titled_navigation_bar: ^3.5.0
  flutter_form_builder: ^3.14.1
  image_picker: ^0.6.3+1
  expandable: ^4.1.2
  google_maps_flutter: ^1.2.0
  geolocator: ^5.3.2+2
  shared_preferences: ^0.5.12
  sailor: ^0.6.0
  flutter_secure_storage:
  http: ^0.12.0+3
  fluttertoast: ^7.1.8
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  dio: ^3.0.8
  auto_size_text: ^2.1.0
  intl: ^0.16.1
  carousel_slider: ^3.0.0
  url_launcher: ^5.4.2
  custom_navigator: ^0.3.0
  persistent_bottom_nav_bar: ^3.0.0
  flutter_icons: ^1.1.0
  async_loader: ^0.1.2
  extended_image: ^2.0.0
  multi_image_picker: ^4.7.14
  event_bus: ^1.1.1
  share: ^0.6.4+3
  dio_http_cache: ^0.2.8
  flutter_phoenix: ^0.1.0
  wheel_chooser: ^0.1.0
  flutter_webview_plugin: ^ 0.4.0
  select_dialog: ^1.1.0
  permission_handler: ^5.0.1+1
  liquid_pull_to_refresh: ^2.0.0
  progress_dialog: ^1.2.4
  google_fonts: ^1.1.0
  material_segmented_control: ^2.1.0+1
  timeago: ^2.0.26
  flutter_xlider: ^3.4.0
  onesignal_flutter: ^2.6.3
  keyboard_actions: ^3.3.0+1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.4
  shimmer: ^1.1.1
  apple_sign_in: ^0.1.0
  sign_in_with_apple: ^2.5.4
  flutter_signin_button: ^1.1.0
  country_code: ^0.1.1
  awesome_dialog: ^1.2.0
  progress_indicators: ^0.1.5
  custom_radio_grouped_button: ^1.0.6+1
  cached_network_image: ^2.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/daafees_icon.jpeg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - langs/
    - images/
    - images/carlogos/
    - images/categories/
    - images/mapicons/
    - images/services/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
